#!/data/data/com.termux/files/usr/bin/bash
set -euo pipefail

# walsave.sh - archive the latest AI-generated wallpaper
#
# Usage: walsave.sh
# Dependencies: exiftool
# Output: copies the most recent wallpaper generated by wallai to
#          ~/pictures/saved-generated-wallpapers with the prompt in the
#          Comment metadata field
# TAG: wallpaper

save_dir="$HOME/pictures/generated-wallpapers"
log_file="$save_dir/wallai.log"
dest_dir="$HOME/pictures/saved-generated-wallpapers"

command -v exiftool >/dev/null 2>&1 || {
  echo "❌ exiftool is required" >&2
  exit 1
}

if [ ! -f "$log_file" ]; then
  echo "❌ No wallpaper has been generated yet" >&2
  exit 1
fi

last_entry=$(tail -n1 "$log_file")
file=$(printf '%s' "$last_entry" | cut -d'|' -f1)
prompt=$(printf '%s' "$last_entry" | cut -d'|' -f2-)
source_file="$save_dir/$file"

if [ ! -f "$source_file" ]; then
  echo "❌ Wallpaper file $source_file not found" >&2
  exit 1
fi

mkdir -p "$dest_dir"
dest="$dest_dir/$(basename "$source_file")"
cp "$source_file" "$dest"
exiftool -overwrite_original -Comment="$prompt" "$dest" >/dev/null

echo "📂 Archived wallpaper to: $dest"
