name: Upload installer

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract upload URL
        id: vars
        run: echo "url=${GITHUB_EVENT_RELEASE_UPLOAD_URL%%\{*}" >> $GITHUB_OUTPUT
        env:
          GITHUB_EVENT_RELEASE_UPLOAD_URL: ${{ github.event.release.upload_url }}

      - name: Upload installer
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.vars.outputs.url }}
          asset_path: scripts/installer.sh
          asset_name: installer.sh
          asset_content_type: application/x-sh
