name: Upload installer

on:
  release:
    types: [published, prereleased]

permissions:
  contents: write

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Upload bleeding edge installer
        if: github.event.release.prerelease == true
        uses: softprops/action-gh-release@v1
        with:
          files: scripts/testing_installer.sh#installer.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload stable installer
        if: github.event.release.prerelease != true
        uses: softprops/action-gh-release@v1
        with:
          files: scripts/installer.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
