name: Upload installer

on:
  release:
    types: [published, prereleased]

permissions:
  contents: write

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Sanitize upload URL
        id: sanitize
        run: |
          echo "url=${UPLOAD_URL%%\{*}" >> $GITHUB_OUTPUT
        env:
          UPLOAD_URL: ${{ github.event.release.upload_url }}

      - name: Upload installer
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.sanitize.outputs.url }}
          asset_path: scripts/installer.sh
          asset_name: installer.sh
          asset_content_type: application/x-sh
